# Generated by Django 4.1.7 on 2023-06-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HistoryEurope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyeurope',
            name='Country_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Blog/'),
        ),
    ]
