# Generated by Django 4.1.7 on 2023-06-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_title', models.CharField(max_length=50)),
                ('Food_desc', models.TextField()),
                ('Food_img', models.FileField(default=None, max_length=250, null=True, upload_to='Blog/')),
            ],
        ),
    ]
